name: pypi-publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag/version to publish
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Extract the version to 'version' based on workflow_dispatch or triggered tag in the published event
      - name: Extract version
        shell: bash
        run: |
          if [ "${{ github.event.inputs.tag }}" != "" ]; then
            echo "::set-output name=tag::$(echo ${{ github.event.inputs.tag }} | sed s/^v//)"
          else
            echo "::set-output name=tag::$(echo ${GITHUB_REF##*/} | sed s/^v//)"
          fi
        id: version

      - name: Python build and make package
        run: python setup.py sdist boto_s3_router
        environment:
          VERSION: ${{ steps.version.outputs.tag }}

      - name: Python publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
          verbose: true
